# =============================================================================
# Training Configuration
# =============================================================================

# Training settings
feature_extractor: resnet50
batch_size: 32
epochs: 300 #1
num_workers: 0
learning_rate: 1e-3
weight_decay: 1e-4
train_tag: 'test_metrics'

# =============================================================================
# Data Configuration
# =============================================================================

# Data paths
data_base_path: 'data/original'
data_image_path: 'texture_image'
data_label_path: 'ParticipantData.csv'
save_texture_maps: false

# Input type (choose one)
#   texture_image: use texture image only
#   texture_maps: use height map and normal map with texture image
dataset_input: texture_maps

# Output type (choose one)
#   roughness: predict roughness value only
#   four_HAs: predict four haptic attributes:
#     - rough-smooth
#     - flat-bumpy
#     - sticky-slippery
#     - hard-soft
dataset_output: roughness

# =============================================================================
# Model Configuration
# =============================================================================

# Model options:
#   1. lr           : Linear Regressor
#   2. svr          : Support Vector Regressor
#   3. ann          : Artificial Neural Network
#   4. cnn_1d_scirep: 1D-CNN (Taye et al.)
#   5. cnn_1d_4ha   : 1D-CNN (Hassan et al.)
#   6. transformer  : Proposed Transformer Regressor 
model: transformer #cnn_1d_4ha