# Configuration for training
feature_extractor: resnet50

batch_size: 8
epochs: 300
num_workers: 0
learning_rate: 1e-3
weight_decay: 1e-4

train_type: 'baseline_train_loocv_4HA'

data_base_path: 'data/original'
data_image_path: 'texture_image'
data_label_path: 'ParticipantData.csv'

save_texture_maps: False

# There are 2 options for input:
#    texture_image: use texture image only
#    texture_maps: use height map and normal map with texture image
dataset_input: texture_maps
# There are 2 options for output:
#    roughness: predict roughness value only
#    four_HAs: predict four haptic attributes below
#        rough-smooth
#        flat-bumpy
#        sticky-slippery
#        hard-soft
dataset_output: four_HAs

# Choose Model 
# 1. lr: linear regressor
# 2. svr: support vector regressor
# 3. ann: artificial neural network
# 4. cnn_1d_scirep: 1D-CNN from Taye et al.
# 5. cnn_1d_4ha: 1D-CNN from Hassan et al.
# 6. proposed model (TBD)
model: cnn_1d_4ha