# Default configuration for training
feature_extractor: resnet50
batch_size: 8
num_epochs: 100
image_size: 560
num_workers: 0
cache_root: feature_cache

# other options you may add later:
# learning_rate: 1e-4
# dataset paths, augmentations, etc.

extraction_batch_size: 8
extraction_num_workers: 2
extraction_use_multiprocessing: false
